/**
 * The single state shape every mode produces.
 *
 * LIVE, REPLAY and SIMULATED all render through this type, so the UI has no idea which
 * one it is showing. That is deliberate: it means the simulated path cannot drift into
 * looking better than the real one, and the real one cannot be quietly special-cased.
 * Provenance travels with the data instead of with the component.
 */

export type Mode = "live" | "replay" | "simulated";

/** Where a value came from. Rendered, never inferred. */
export type Provenance =
  | "proof" // a verified cross-chain inclusion proof
  | "chain" // read directly from chain state
  | "replay" // a genuine captured proof, replayed
  | "simulated"; // generated by the scenario engine

export type Health = "proven" | "breached" | "stale" | "unknown";

export interface SolvencyState {
  /** Last cryptographically proven source-chain balance, in base units. */
  verifiedReserve: bigint;
  /** Announced-but-unexecuted withdrawals, already excluded from backing. */
  encumberedReserve: bigint;
  /** Wrapped totalSupply on Creditcoin — the liabilities. */
  outstandingSupply: bigint;
  /** verifiedReserve * haircut, the actual ceiling on supply. */
  discountedReserve: bigint;
  /** Headroom left before the bound. */
  maxMintable: bigint;
  /** Coverage in bps. 10000 = exactly 100%. */
  collateralRatioBps: number;

  haircutBps: number;
  epoch: number;

  attestedAtHeight: number;
  latestAttestedHeight: number;
  stalenessBlocks: number;
  maxStalenessBlocks: number;

  fresh: boolean;
  solvent: boolean;
  mintFrozen: boolean;

  decimals: number;
  symbol: string;
  /** Off-chain parties this asset's reserve figure depends on. 0 when proven. */
  trustedParties: number;
}

export interface LedgerEntry {
  id: string;
  at: number;
  kind:
    | "ReserveProven"
    | "Minted"
    | "InvariantChecked"
    | "SolvencyBreach"
    | "RedeemRequested"
    | "Rejected"
    | "Snapshot"
    | "Info";
  title: string;
  detail: string;
  provenance: Provenance;
  /** Set when the entry represents a rejected attack — drives "THE BOUND HELD". */
  held?: boolean;
  txHash?: string;
  explorerUrl?: string;
}

/** One step in the mint authorization path, and what it costs in trust. */
export interface TrustStep {
  label: string;
  mechanism: string;
  status: "proven" | "enforced" | "pending" | "failed";
  /** Number of off-chain parties that must be trusted for this step. Always 0. */
  trustedParties: number;
}

export interface DashboardSnapshot {
  mode: Mode;
  connected: boolean;
  health: Health;
  state: SolvencyState;
  ledger: LedgerEntry[];
  trustPath: TrustStep[];
  /** Live-mode chain context. */
  context: {
    creditcoinChainId?: number;
    sourceChainKey?: number;
    ascAddress?: string;
    vaultAddress?: string;
    sourceAsset?: string;
    wrappedAddress?: string;
    sourceHead?: number;
    vaultBalance?: bigint;
  };
  /** Side-by-side comparison of reported vs proven reserve. */
  divergence?: {
    reportedAnswer: bigint;
    reportedAgeSeconds: number;
    provenAnswer: bigint;
    provenAgeSeconds: number;
  };
  /** Source-chain vault safety posture. */
  vault?: {
    emergencyEnabled: boolean;
    withdrawalDelayBlocks: number;
    encumbered: bigint;
  };
  /** Populated when a mode cannot reach its data source. */
  error?: string;
  /** Simulated mode only: which act of the demo script is showing. */
  act?: { index: number; total: number; name: string; caption: string };
}

export const EMPTY_STATE: SolvencyState = {
  verifiedReserve: 0n,
  encumberedReserve: 0n,
  outstandingSupply: 0n,
  discountedReserve: 0n,
  maxMintable: 0n,
  collateralRatioBps: 0,
  haircutBps: 10000,
  epoch: 0,
  attestedAtHeight: 0,
  latestAttestedHeight: 0,
  stalenessBlocks: 0,
  maxStalenessBlocks: 200,
  fresh: false,
  solvent: false,
  mintFrozen: false,
  decimals: 18,
  symbol: "wmTUSD",
  trustedParties: 0,
};

export function healthOf(s: SolvencyState): Health {
  if (s.attestedAtHeight === 0) return "unknown";
  if (!s.solvent || s.mintFrozen) return "breached";
  if (!s.fresh) return "stale";
  return "proven";
}

/** The trust path, derived from live state. Every step terminates at zero. */
export function buildTrustPath(s: SolvencyState, health: Health): TrustStep[] {
  const proven = s.attestedAtHeight > 0;
  return [
    {
      label: "Source event",
      mechanism: "Included in an Ethereum Sepolia block",
      status: proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Merkle inclusion",
      mechanism: "Block Prover precompile 0x0FD2",
      status: proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Continuity",
      mechanism: "Attested chain of block digests",
      status: proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Receipt status",
      mechanism: "receiptStatus == 1 checked on-chain",
      status: proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Emitter binding",
      mechanism: "Log emitter == canonical vault",
      status: proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Freshness",
      mechanism: "ChainInfo precompile 0x0FD3",
      status: health === "stale" ? "failed" : proven ? "proven" : "pending",
      trustedParties: 0,
    },
    {
      label: "Announced exits",
      mechanism: "Withdrawals timelocked and de-rated before funds move",
      status: proven ? "enforced" : "pending",
      trustedParties: 0,
    },
    {
      label: "Aggregate bound",
      mechanism: "supply + amount <= reserve x haircut",
      status: health === "breached" ? "failed" : proven ? "enforced" : "pending",
      trustedParties: 0,
    },
  ];
}
